spring:
  application:
    name: learn-graphql-java

server:
  http2:
    enabled: true

graphql:
  playground:
    endpoint: /graphql
    subscriptionEndpoint: /subscriptions
    enabled: true
    pageTitle: Playground
    cdn:
      enabled: false
      version: latest